name: news_app_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  get: ^4.6.6
  email_validator: ^2.1.17
  cached_network_image:
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_storage: ^11.2.8
  image_picker: ^1.0.4
  path: ^1.8.3
  google_sign_in: ^6.1.5
  intl_phone_field: ^3.2.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
